project_id = "msbphnimxpohgwbnqwoo"

[functions.send-notification]
verify_jwt = false

[functions.process-webhook]
verify_jwt = false

[functions.analytics-summary]
verify_jwt = true

[functions.log-performance]
verify_jwt = true

[functions.cache-invalidation]
verify_jwt = false
