// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msbphnimxpohgwbnqwoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zYnBobmlteHBvaGd3Ym5xd29vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjYzOTgsImV4cCI6MjA3Mjc0MjM5OH0.bPUQjBWpk33qn3aPm8QvXg4JdY06BLhxqeDqrJX2VPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});